chore: Disable music link event listener
NLLCommunity/discord-norsk-bott pull request #72
Opened 2024-10-02 20:48 UTC by myrkvi

Disables the event listener that triggers the music-link feature of Norsk-bott.
Temporary measure while figuring out a way to provide this feature in a less invasive manner.

disclaimer: i know very little about the codebase here, but removing the export seemed to do the trick for DI not to be able to include it anymore :shrug: 

Did a poll in #server-suggestions on NLL after a new request to remove the music linking feature from a user. Majority believes that the aspect of how the bot links various music services can be improved, to be e.g. a message sent upon request (ephemerally).

2024-10-03 06:06 UTC, myrkvi commented
> Den rette måten å gjera dette på er å leggje til ein `.except(...)` i hovudmodulen (app.module.ts) under `providers`.

Den er grei, skal ordne det når eg er ferdig på arbeid, takk! :)

2024-10-04 12:52 UTC, adalinesimonian requested changes

2024-10-04 12:52 UTC, adalinesimonian commented on src/app.module.ts
> +      NestClassCollection.fromInjectables(handlers).except(
Legg dette til etter .concat og før .toArray, ikkje her (og ikkje gløym å formattere med prettier

2024-10-05 03:37 UTC, adalinesimonian approved these changes

2024-10-06 09:20 UTC, merged